"""Add chat history enhancements: metadata, soft delete, sequence ordering, and indexes

Revision ID: a2f80585e147
Revises: 
Create Date: 2025-10-26 16:33:00.330022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2f80585e147'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('sequence', sa.Integer(), nullable=True))
    op.add_column('chat_messages', sa.Column('tokens_used', sa.Integer(), nullable=True))
    op.add_column('chat_messages', sa.Column('model_version', sa.String(length=50), nullable=True))
    op.add_column('chat_messages', sa.Column('context_documents', sa.JSON(), nullable=True))
    op.add_column('chat_messages', sa.Column('message_metadata', sa.JSON(), nullable=True))
    op.add_column('chat_messages', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_timestamp'), 'chat_messages', ['timestamp'], unique=False)
    op.add_column('chat_sessions', sa.Column('message_count', sa.Integer(), nullable=True))
    op.add_column('chat_sessions', sa.Column('total_tokens', sa.Integer(), nullable=True))
    op.add_column('chat_sessions', sa.Column('session_metadata', sa.JSON(), nullable=True))
    op.add_column('chat_sessions', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_chat_sessions_last_activity'), 'chat_sessions', ['last_activity'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_last_activity'), table_name='chat_sessions')
    op.drop_column('chat_sessions', 'deleted_at')
    op.drop_column('chat_sessions', 'session_metadata')
    op.drop_column('chat_sessions', 'total_tokens')
    op.drop_column('chat_sessions', 'message_count')
    op.drop_index(op.f('ix_chat_messages_timestamp'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_column('chat_messages', 'deleted_at')
    op.drop_column('chat_messages', 'message_metadata')
    op.drop_column('chat_messages', 'context_documents')
    op.drop_column('chat_messages', 'model_version')
    op.drop_column('chat_messages', 'tokens_used')
    op.drop_column('chat_messages', 'sequence')
    # ### end Alembic commands ###
